<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>scroll</name>
   <tag></tag>
   <elementGuidId>7f124f73-5b74-42a4-a0e4-06d8d6d991ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[.='Bismillahirrahmanirrahim']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[.='Bismillahirrahmanirrahim']</value>
   </webElementProperties>
</WebElementEntity>
